### ISSUE TITLE
Error in pdata.frame(., index = c("Country", "Year")) : already a pdata.frame

### ISSUE THREAD

**Issue by Griffin97** [alinacherkas/MA-Thesis#1]
Greetings Alina, i am trying to replicate your work using the Rmd file you have provided.

the following code for Table 3 isn't running smoothly as the result cannot proceed to the next code
![Screenshot 2023-02-27 at 23 34 26](https://user-images.githubusercontent.com/68814810/221607967-fa70dd57-6092-407d-adac-08f8fff91b5e.png)

**Comment by alinacherkas** [comment]
Hi @Griffin97, this error may be due to the differences in the versions of R packages I used 3 years ago and the ones available today. It can be fixed by adding `as_tibble()` after the `filter(IV_Sample == TRUE` in the screenshot above. I have just pushed an update that includes this fix and package versions I tested it with. Hope this helps.

**Comment by Griffin97** [comment]
Thank you, will try it out and let you know my progress .

Thanks alot for your reply .
